name: build via Nix

inputs:
  package:
    description: package specification to build
    required: true
  install-path:
    description: path within resulting output, from which to install (e.g. `/bin/wit-deps`)

runs:
  using: composite
  steps:
  - run: nix build -L '.#${{ inputs.package }}'
    shell: bash
  - run: nix run -L --inputs-from . 'nixpkgs#coreutils' -- --coreutils-prog=ginstall -p "./result${{ inputs.install-path }}" '${{ inputs.package }}'
    shell: bash
  - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
    with:
      name: ${{ inputs.package }}
      path: ${{ inputs.package }}
      if-no-files-found: error
