name: build via Nix

inputs:
  package:
    description: package specification to build
    required: true
  install-path:
    description: path within resulting output, from which to install (e.g. `/bin/wit-deps`)

runs:
  using: composite
  steps:
  - run: nix build -L '.#${{ inputs.package }}'
    shell: bash
  - run: nix run -L --inputs-from . 'nixpkgs#coreutils' -- --coreutils-prog=ginstall -p "./result${{ inputs.install-path }}" '${{ inputs.package }}'
    shell: bash
  - uses: actions/upload-artifact@84480863f228bb9747b473957fcc9e309aa96097 # v4.4.2
    with:
      name: ${{ inputs.package }}
      path: ${{ inputs.package }}
      if-no-files-found: error
