package examples:github;

world github {
    import wasi:clocks/monotonic-clock@0.2.8;
    import wasi:http/incoming-handler@0.2.8;
    import wasi:sockets/network@0.2.8;
    import wasi:keyvalue/store@0.2.0-draft;
}
