name: nix

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
    - uses: ./.github/actions/install-nix
      with: 
        cachixAuthToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix fmt -L $(find . -type f -name '*.nix')

  run:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
    - uses: ./.github/actions/install-nix
      with: 
        cachixAuthToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix run -L . -- --version

  develop:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
    - uses: ./.github/actions/install-nix
      with: 
        cachixAuthToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix develop -L --ignore-environment -c cargo tree

  check:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
    - uses: ./.github/actions/install-nix
      with: 
        cachixAuthToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        nix build -L \
        .#checks.x86_64-linux.cli \
        .#checks.x86_64-linux.clocks \
        .#checks.x86_64-linux.filesystem \
        .#checks.x86_64-linux.http \
        .#checks.x86_64-linux.io \
        .#checks.x86_64-linux.random \
        .#checks.x86_64-linux.sockets
